# application.yml
reports:
  captureOnSuccess: false
  captureFailuresInPdf: true
  title: "MyApp Test Report"
  #reportPath: "reports/"
  reportPath: "target/test-output/reports/"
  screenshotsPath: "target/test-output/screenshots/"
  pdfPath: "target/test-output/pdfs/"
  logsPath: "target/test-output/logs/"
  captureLogsInFile: true
  theme: dark

applicationConfig:
  name: "myapp-functional-automation"
  baseUrl: "https://ecommerce-playground.lambdatest.io/index.php/"
  retryCount: 2
  logLevel: INFO
  environment: qa
  timeout: 10
  browserConfig:
    name: chrome
    headless: true
    timeout: 5

notifications:
  email:
    enabled: false
    recipients:
      - prabhukumarp@gmail.com
      - test@gmail.com
    smtp:
      host: smtp.example.com
      port: 587
      username: user@example.com
      password: encrypted_password_here
  teams:
    enabled: false
    webhookUrl: https://outlook.office.com/webhook/

database:
  enabled: false
  name: postgres
  defaultSchema: public

playwright:
  takeScreenshots: true
  recordVideo: false
  trace: retain-on-failure
debug:
  writeMergedConfig: false #Used in ConfigLoader to debug if the config files are merges correctly based on environment
